name: octave-fem
channels:
  - conda-forge
dependencies:
  - python=3.13
  - notebook>=6.4,<7
  - jupyterlab>=4.0
  - jupyter_contrib_nbextensions
  - octave_kernel
  - octave
  - gnuplot
  - texinfo
  - rise
  - nodejs  # Required for JupyterLab extensions
  - pip
  - pip:
    - jupyterlab-rise